name: kooka_sing
description: Kooka Sing - Duolingo-style singing learning app built with Flutter
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies for ROO implementation
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/kooka-burra-singing.png
    - img/kooka-burra-waiving.png



